Fixed JavaScript SDK error reporting when no command handler is registered
When no command handler for a particular gRPC method is registered in
the JavaScript SDK, the error reporting currently throws the following
exception:

```
TypeError: Cannot read property 'commandHandlers' of undefined
```

This is due to the thing generating the message relying on a property
that doesn't exist. Hence, the original error gets lost. This fixes
that.